run_name: exp_fingertap_vitb_phoneaug
backbone: vjepa2_1_vitb_384
predict_per_item: 64

wandb:
  key: 9ce4b10bf35b56281619a07601ec9c274604c9f6
  entity: sposiboh
  project: dikiy

model:
  fc_drop_rate: 0.5
  class_weights: inv_freq_sqrt
  freeze_encoder_layers: 10

data:
  prefix: /root/data/fingertap_with_negs
  label_json: /root/labels/hubu_negs_train_cleanval.json
  chunk_length: 64
  chunk_shift: 32
  chunk_step: 1
  resize_to: 256
  resize_style: square
  do_aa: true
  aug_profile: phone
  part_sample: 1
  subsample_keep_rare_threshold: null
  cache_entire_dataset: true

training:
  epochs: 10
  train_bs: 8
  val_bs: 8
  num_workers: 8
  part_warmup: 0.2
  lr: 4.0e-5
  weight_decay: 0.1
  label_smoothing: 0.1
  compile: true
  patience: 3

mixup_alpha: 0.8
target_noise_std: 0.0
ema_decay: null
seed: 0
device: cuda
starting_checkpoint: null
max_batches: null
multilabel_threshold: 0.85
