run_name: mabe_beetle_same_loss
model_name: "HuggingFaceTB/SmolVLM2-500M-Instruct"
predict_per_item: 16
data:
  prefix: "/mnt/aperto/peter/feral_data/mabe_beetle/reencoded"
  label_json: "/mnt/aperto/peter/feral_data/mabe_beetle/fix_mabe_beetle_labels.json"
  chunk_length: 16
  chunk_shift: 8
  resize_to: 256
  do_aa: true
training:
  epochs: 10
  train_bs: 16
  val_bs: 32
  num_workers: 10
  warmup_epochs: 2
  lr: 4.0e-5
  weight_decay: 0.1
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
