run_name: rerun_beetle
model_name: "facebook/vjepa2-vitl-fpc16-256-ssv2"
predict_per_item: 64
model:
  fc_drop_rate: 0.5
  class_weights: null
data:
  prefix: "/home/petr/home_datasets/reencoded_mabe_beetle"
  label_json: "/home/petr/home_datasets/all_configs/fix_mabe_beetle_labels.json"
  chunk_length: 64
  chunk_shift: 32
  chunk_step: 1
  resize_to: 256
  do_aa: true
training:
  epochs: 10
  train_bs: 4
  val_bs: 8
  num_workers: 12
  part_warmup: 0.2
  lr: 4.0e-5
  weight_decay: 0.1
  label_smoothing: 0.1
  compile: false
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
device: "cuda"
wandb:
  key: dde17687b4b84ba8171dfede64d865243be41a0e
  entity: sposiboh
  project: feral_public