run_name: ahen_calms
model_name: "HuggingFaceTB/SmolVLM2-500M-Instruct"
predict_per_item: 16
data:
  prefix: "/mnt/aperto/peter/feral_data/calms/all_raw"
  label_json: "/mnt/aperto/peter/feral_data/calms/calms_labels.json"
  cache_dir: "/mnt/aperto/peter/feral_data/calms/cache256"
  chunk_length: 16
  chunk_shift: 8
  resize_to: 256
  do_aa: true
  preproc_processes: 10
training:
  epochs: 10
  train_bs: 16
  val_bs: 32
  num_workers: 10
  warmup_epochs: 2
  lr: 4.0e-5
  weight_decay: 0.1
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
